# Generated by Django 5.2.1 on 2025-05-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollapp', '0002_variant_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='total_votes',
            field=models.IntegerField(default=0),
        ),
    ]
